from tkinter import *
# window=Tk()
# btn1=Button(window,text='버튼1')
# btn2=Button(window,text='버튼2')
# btn3=Button(window,text='버튼3')
# # btn1.pack(side=LEFT)
# # btn2.pack(side=LEFT)
# # btn3.pack(side=LEFT)
# btn1.pack(side=BOTTOM,padx=10,pady=10)
# btn2.pack(side=BOTTOM,fill=X,padx=10,pady=10,ipadx=10,ipady=10)
# btn3.pack(side=BOTTOM,padx=10,pady=10,ipadx=10,ipady=10)
# window.mainloop()
#--상대위치:pack()-----------------------------
# window=Tk()
# window.title("Python Study")
# window.geometry("600x500")
# window.resizable(False,False)
# b1=Button(window,text="top_1")
# b2=Button(window,text="top_2")
# b3=Button(window,text="bottom_1")
# b4=Button(window,text="bottom_2")
# b5=Button(window,text="left_1")
# b6=Button(window,text="left_2")
# b7=Button(window,text="right_1")
# b8=Button(window,text="right_2")
# b9=Button(window,text="center",bg='red')
# b1.pack(side="top")
# b2.pack(side="top",fill="x")
# b3.pack(side="bottom")
# b4.pack(side="bottom",anchor='e')
# b5.pack(side="left")
# b6.pack(side="left",fill='y')
# b7.pack(side="right")
# b8.pack(side="right",anchor='s')
# b9.pack(expand=True,fill="both")
# window.mainloop()
#절대위치:place()--------------------
# window=Tk()
# window.geometry("600x500")
# b1=Button(window,text="(50,50)")
# b2=Button(window,text="(50,100)")
# b3=Button(window,text="(100,50)")
# b4=Button(window,text="(0,200)")
# b5=Button(window,text="(0,300)")
# b1.place(x=50,y=50)
# b2.place(x=50,y=100,width=50,height=50)
# b3.place(x=100,y=50)
# b4.place(x=0,y=200,relwidth=0.5)
# b5.place(x=0,y=300,relx=0.7)
# window.mainloop()
# 셀단위 배치:grid()------------------------
window=Tk()
window.geometry("600x500")
window.resizable(False,False)
b1=Button(window,text="(0,0)")
b2=Button(window,text="(0,1)",width=20)
b3=Button(window,text="(0,2)")
b4=Button(window,text="(1,0)")
b5=Button(window,text="(1,1)")
b6=Button(window,text="(1,3)")
b7=Button(window,text="(2,1)")
b8=Button(window,text="(2,2)")
b9=Button(window,text="(2,4)")
b1.grid(row=0,column=0)
b2.grid(row=0,column=1)
b3.grid(row=0,column=2)
b4.grid(row=1,column=0,rowspan=2)
b5.grid(row=1,column=1,columnspan=2)
b6.grid(row=1,column=3)
b7.grid(row=2,column=1,sticky='e')
b8.grid(row=2,column=2)
b9.grid(row=2,column=99)
window.mainloop()










